export enum AgentSkill {
  VISION = 'VISION',
  FILE_UPLOAD = 'FILE_UPLOAD',
  WEB_SEARCH = 'WEB_SEARCH',
  IMAGE_GENERATION = 'IMAGE_GENERATION',
  CODE_INTERPRETER = 'CODE_INTERPRETER',
  CITATIONS = 'CITATIONS',
  USAGE = 'USAGE'
}
